"""create candles table with value and created_at

Revision ID: 392bd68b6961
Revises: bbcd9e03ee39
Create Date: 2026-09-25 12:31:14.751110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392bd68b6961'
down_revision: Union[str, Sequence[str], None] = 'bbcd9e03ee39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle_symbol_tf_ts')
    )
    op.create_index('ix_candle_symbol_tf_ts', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index('ix_candle_symbol_tf_ts', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
