"""create backtest tables

Revision ID: bdb4b66148e7
Revises: 392bd68b6961
Create Date: 2026-09-29 17:28:32.316442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb4b66148e7'
down_revision: Union[str, Sequence[str], None] = '392bd68b6961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('bars', sa.Integer(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('final_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cagr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sharpe', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sortino', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('calmar', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtests_strategy_created', 'backtests', ['strategy', 'created_at'], unique=False)
    op.create_index('ix_backtests_symbol_tf_created', 'backtests', ['symbol', 'timeframe', 'created_at'], unique=False)
    op.create_table('backtest_equity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_equity_backtest_ts', 'backtest_equity', ['backtest_id', 'timestamp'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('bars_held', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl_net', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_trades_backtest_id', 'backtest_trades', ['backtest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_trades_backtest_id', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('ix_backtest_equity_backtest_ts', table_name='backtest_equity')
    op.drop_table('backtest_equity')
    op.drop_index('ix_backtests_symbol_tf_created', table_name='backtests')
    op.drop_index('ix_backtests_strategy_created', table_name='backtests')
    op.drop_table('backtests')
    # ### end Alembic commands ###
